import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

const NeueMetanaNext = localFont({
  src: "../fonts/NeueMetanaNext-SemiBold.otf",
  weight: "100 900",
  variable: "--font-neue-metana-next",
});

export const metadata: Metadata = {
  title: "Stitchify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col ${NeueMetanaNext.variable}`}
      >
        <ThemeProvider attribute="class" storageKey="theme">
          <Navbar />
          <main className="flex-1 pt-24">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
